# Generated by Django 5.2 on 2025-05-04 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_province_alter_category_name_subcategory_province_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategorymedia',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='categories.province'),
        ),
    ]
