# Generated by Django 5.2 on 2025-05-04 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_subcategorymedia_province'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategorymedia',
            name='province',
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.province'),
        ),
    ]
