# Generated by Django 5.2 on 2025-05-04 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_remove_subcategorymedia_province_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='province',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='categories.province'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ProvinceMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10)),
                ('file', models.FileField(upload_to='province_media/')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='categories.province')),
            ],
        ),
        migrations.DeleteModel(
            name='SubCategoryMedia',
        ),
    ]
