# Generated by Django 5.2 on 2025-05-04 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0006_alter_subcategory_province_provincemedia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='province',
        ),
    ]
