# Generated by Django 5.2 on 2025-05-04 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0007_remove_subcategory_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='provincemedia',
            name='subcategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='province_media', to='categories.subcategory'),
            preserve_default=False,
        ),
    ]
