# Generated by Django 5.2 on 2025-05-04 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0008_provincemedia_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10)),
                ('file', models.FileField(upload_to='media/')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='categories.province')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='categories.subcategory')),
            ],
        ),
        migrations.DeleteModel(
            name='ProvinceMedia',
        ),
    ]
